version: 1.0.{build}
branches:
  only:
    - master
image:
- Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2019
- Ubuntu1604
- Previous Ubuntu1604
- macOS
build_script:
- pwsh: |-

    Write-Host "Hello" > testfile
artifacts:
- path: /*
deploy_script:
  - pwsh: |-
 
      $artifacts

      foreach ($artifactName in $artifacts.keys)
      {
          Write-Host $artifacts[$artifactName].path
      }
